### ISSUE TITLE
Error when trying to copy a password

### ISSUE THREAD

**Issue by fpetrovski** [blacs30/bitwarden-alfred-workflow#118]
Whenever I try to copy the password of an Item I receive the following error:

```
14:01:42 workflow.go:343: ------------------ FATAL ERROR -------------------
14:01:42 workflow.go:344: runtime error: slice bounds out of range [:-78] : goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.17.4/x64/src/runtime/debug/stack.go:24 +0x88
github.com/deanishe/awgo.(*Workflow).Run.func2(0x1400000b0e0)
	/Users/runner/go/pkg/mod/github.com/deanishe/awgo@v0.29.1/workflow.go:344 +0xf0
panic({0x1004eede0, 0x140000289a8})
	/Users/runner/hostedtoolcache/go/1.17.4/x64/src/runtime/panic.go:1038 +0x21c
main.unpad(...)
	/Users/runner/work/bitwarden-alfred-workflow/bitwarden-alfred-workflow/src/crypt_util.go:170
main.(*CipherString).Decrypt(0x14000072d80, {{0x140000267c0, 0x20, 0x20}, {0x140000267e0, 0x20, 0x20}, 0x2})
	/Users/runner/work/bitwarden-alfred-workflow/bitwarden-alfred-workflow/src/crypt_util.go:164 +0x4c4
main.(*CipherString).DecryptKey(0x14000072d80, {{0x140000267c0, 0x20, 0x20}, {0x140000267e0, 0x20, 0x20}, 0x2}, 0x0)
	/Users/runner/work/bitwarden-alfred-workflow/bitwarden-alfred-workflow/src/crypt_util.go:61 +0x54
main.MakeDecryptKeyFromSession({0x140000323f0, 0x84}, {0x1400003046b, 0x58})
	/Users/runner/work/bitwarden-alfred-workflow/bitwarden-alfred-workflow/src/crypt.go:220 +0xd40
main.runGetItem()
	/Users/runner/work/bitwarden-alfred-workflow/bitwarden-alfred-workflow/src/bitwarden.go:236 +0x1fc
main.run()
	/Users/runner/work/bitwarden-alfred-workflow/bitwarden-alfred-workflow/src/main.go:264 +0xf54
github.com/deanishe/awgo.(*Workflow).Run(0x1400000b0e0, 0x10050f720)
	/Users/runner/go/pkg/mod/github.com/deanishe/awgo@v0.29.1/workflow.go:358 +0x310
main.main()
	/Users/runner/work/bitwarden-alfred-workflow/bitwarden-alfred-workflow/src/main.go:271 +0x3c
14:01:42 workflow.go:345: ---------------- END STACK TRACE -----------------
 ```

**Comment by blacs30** [comment]
Can you please follow these steps, that should solve the issue

https://github.com/blacs30/bitwarden-alfred-workflow/issues/53#issuecomment-764020805

**Comment by fpetrovski** [comment]
Thanks that got it working for me. I see you've added this fix in the readme as a workaround for another issue, perhaps you can include that updating the key also fixes this issue.
