### ISSUE TITLE
argon2.node, mach-o file, but is an incompatible architecture

### ISSUE THREAD

**Issue by leikoilja** [blacs30/bitwarden-alfred-workflow#155]
Installing the workflow on M1 macOS 13.3.1 using either login/password or API auth I am getting this error:

> Passing output 'Login to Bitwarden failed. Error:
> internal/modules/cjs/loader.js:1122  return process.dlopen(module, path.toNamespacedPath(filename));                 ^Error: dlopen(/Users/leikoilja/.nvm/versions/node/v18.16.0/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node, 0x0001): tried: '/Users/leikoilja/.nvm/versions/node/v18.16.0/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/leikoilja/.nvm/versions/node/v18.16.0/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node' (no such file), '/Users/leikoilja/.nvm/versions/node/v18.16.0/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)    at Module.load (internal/modules/cjs/loader.js:928:32)    at Function.Module._load (internal/modules/cjs/loader.js:769:14)    at Module.require (internal/modules/cjs/loader.js:952:19)    at require (internal/modules/cjs/helpers.js:88:18)    at Object.<anonymous> (/Users/leikoilja/.nvm/versions/node/v18.16.0/lib/node_modules/@bitwarden/cli/node_modules/argon2/argon2.js:9:25)    at Module._compile (internal/modules/cjs/loader.js:1063:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)    at Module.load (internal/modules/cjs/loader.js:928:32)    at Function.Module._load (internal/modules/cjs/loader.js:769:14)'
> 

node versions v18.16, bw version 2023.4.0

Any idea where i can try taking a look at? 🤔

**Comment by blacs30** [comment]
Have you tried to set the PATH manually in the workflow env settings?

**Comment by leikoilja** [comment]
yes sir, @blacs30 :) 
i was wondering if it may have anything to do with the error message for `argon2`, since i m running it on Mac M1 (arm chip) 🤔

**Comment by blacs30** [comment]
I ran the workflow in the past on M1, currently i don't have one available for testing. Not sure about the argon2 error.
:(

**Comment by leikoilja** [comment]
oh, sad sad. Any advice where i can get started debugging or trying things? Does the workflow work with node 18?
